name: ethereum_address
description: A dart library to generate, checksum, and validate Ethereum addresses
version: 1.0.1
homepage: https://github.com/petejkim/dart-ethereum_address

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  convert: ^3.0.1
  pointycastle: ^3.4.0
  # convert: ^2.1.1
  # pointycastle: ^1.0.2

dev_dependencies:
  test: ^1.19.5
